name: 'changed-files'
description: 'Action to check the changed files'
inputs:
  access_token:
    description: 'Access token to use the gh cli'
    required: true
  required_paths:
    description: 'List of required paths separated by a comma using the glob format'
    required: false
runs:
  using: 'node16'
  main: 'index.js'