name: 'action-docker-build'
description: 'Action to build a docker image'
outputs:
  github_branch:
    description: 'Github branch name in lowercase'
  github_branch_id:
    description: 'Task ID in lowercase'
inputs:
  user_name:
    description: 'Name of the git user to push the changes'
    required: true
  user_email:
    description: 'Email of the git user to push the changes'
    required: true
  node_version:
    description: 'node version used for the node commands'
    required: false
    default: '16'
  npm_version:
    description: 'npm version used for the npm commands'
    required: false
    default: '8.5'
runs:
  using: 'composite'
  env:
    NODE_VERSION: 16
  steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ github.event.inputs.node_version }}
      - name: Checkout
        uses: actions/checkout@v2

