name: "better-dependabot"
description: "Update NPM Packages and Create PR"
inputs:
  node_version:
    description: 'node version used for the node commands'
    required: false
    default: 'lts/*'
  npm_version:
    description: 'npm version used for the npm commands'
    required: false
    default: ''
  version_target:
    description: 'Determines the version to upgrade to: latest, newest, greatest, minor, patch, semver. (default: patch)'
    required: false
    default: 'patch'
  ncu_args:
    descriptions: 'Extra args for the npm-check-updates'
    required: false
    type: string
  token:
    description: 'A Github PAT'
    required: true
  target_branch:
    description: 'The PR target branch'
    default: 'main'
    required: false
runs:
  using: 'composite'
  steps:

    - name: Check for Existing Pull Requests
      id: check_pr
      run: |
        BRANCH_PREFIX="better-dependabot-updates-${{ inputs.version_target }}"
        BRANCH_NAME=$BRANCH_PREFIX-$(date +%Y%m%d%H%M%S)
        PR_EXISTS=$(gh pr list --search "head:${BRANCH_PREFIX} type:pr state:open" | wc -l)
        echo "PR_EXISTS=${PR_EXISTS}" >> $GITHUB_ENV
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "pr_exists=${PR_EXISTS}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Install node
      if: steps.check_pr.outputs.pr_exists == '0'
      uses: Drassil/gh-actions-collection/extra-info@master
      id: prepare
      with:
        npm_version: ${{ inputs.npm_version }}
        node_version: ${{ inputs.node_version }}

    - name: Install npm-check-updates
      if: steps.check_pr.outputs.pr_exists == '0'
      shell: bash
      run: npm install -g npm-check-updates

    - name: Check npm updates
      if: steps.check_pr.outputs.pr_exists == '0'
      shell: bash
      run: ncu --target ${{ inputs.version_target }} ${{ inputs.ncu_args }}

    - name: Update package.json
      if: steps.check_pr.outputs.pr_exists == '0'
      shell: bash
      run: ncu -u --target ${{ inputs.version_target }} ${{ inputs.ncu_args }}

    - name: Install updated packages
      if: steps.check_pr.outputs.pr_exists == '0'
      shell: bash
      run: npm install --package-lock-only

    - name: Check for Changes
      if: steps.check_pr.outputs.pr_exists == '0'
      id: check_changes
      run: |
        if git diff --quiet && git diff --staged --quiet; then
          echo "NO_CHANGES=true" >> $GITHUB_ENV
        else
          echo "NO_CHANGES=false" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Create a new branch
      if: steps.check_pr.outputs.pr_exists == '0' && env.NO_CHANGES == 'false'
      run: |
        git checkout -b $BRANCH_NAME
      shell: bash

    - name: Commit changes
      if: steps.check_pr.outputs.pr_exists == '0' && env.NO_CHANGES == 'false'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add --all
        git commit -m "Update dependencies"
        git push --set-upstream origin $BRANCH_NAME
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Create Pull Request
      if: steps.check_pr.outputs.pr_exists == '0' && env.NO_CHANGES == 'false'
      run: |
        gh pr create --title "Better Dependabot: Update ${{ inputs.version_target }} dependencies" --body "This PR updates dependencies to the most recent ${{ inputs.version_target }} versions." --head $BRANCH_NAME --base ${{ inputs.target_branch }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

