name: 'action-extra-info'
description: 'It injects in your pipeline extra info that can be used by your workflows'
outputs:
  github_branch:
    description: 'Github branch name'
  package_version:
    description: 'The package version of the repository. PACKAGE_VERSION env variable is also exported.'
inputs:
  node_version:
    description: 'node version used for the node commands'
    required: false
    default: '16'
  npm_version:
    description: 'npm version used for the npm commands'
    required: falses
    default: '8.5'
  package_json_path:
    description: 'Path of the package.json to retrieve the package version'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ github.event.inputs.node_version }}
    - name: Prepare
      shell: bash
      env:
        # needed because of this bug: https://github.com/actions/runner/issues/665
        INPUT_NODE_VERSION: ${{ inputs.node_version }}
        INPUT_NPM_VERSION: ${{ inputs.npm_version }}
        INPUT_PACKAGE_JSON_PATH: ${{ inputs.package_json_path }}
      run: |
        node "${{ github.action_path }}/index.js"
