name: Test github actions collection
on:
  pull_request:
  push:
    branches:
      - master
env:
  NODE_VERSION: 16
  NPM_VERSION: 8.5
jobs:
  test-local-usage:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Test extra-info action
        with:
          npm_version: ${{ env.NPM_VERSION }}
          node_version: ${{ env.NODE_VERSION }}
        uses: ./extra-info
  test-remote-usage:
    runs-on: [ubuntu-latest]
    steps:
      - name: Test extra-info action
        with:
          npm_version: ${{ env.NPM_VERSION }}
          node_version: ${{ env.NODE_VERSION }}
          package_json_path: ../package.json
        uses: Drassil/gh-actions-collection/extra-info@master
