name: Test github actions collection
on:
  pull_request:
  push:
    branches:
      - master
env:
  NODE_VERSION: 16
  NPM_VERSION: 8
jobs:
  test-extra-info-local-usage:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Test extra-info action
        with:
          npm_version: ${{ env.NPM_VERSION }}
          node_version: ${{ env.NODE_VERSION }}
        uses: ./extra-info

  test-extra-info-remote-usage:
    runs-on: [ubuntu-latest]
    steps:
      - name: Test extra-info action
        with:
          npm_version: ${{ env.NPM_VERSION }}
          node_version: ${{ env.NODE_VERSION }}
          package_json_path: ../package.json
        uses: Drassil/gh-actions-collection/extra-info@master

  test-node-setup:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Test node-setup action
        with:
          npm_version: ${{ env.NPM_VERSION }}
          node_version: ${{ env.NODE_VERSION }}
          project_id: 'test-node-setup'
          install_command: 'ci'
        uses: ./node-setup
  
  test-node-setup-default-values:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Test node-setup action
        with:
          project_id: 'test-node-setup'
        uses: ./node-setup
