name: Automated Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at 00:00
  workflow_dispatch: # Allows manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Better Dependabot
        uses: Drassil/gh-actions-collection/better-dependabot@master
        with:
          version_target: 'patch' # Example: target minor version updates
          token: ${{ secrets.GITHUB_TOKEN }} # Use a GitHub PAT or `${{ secrets.GITHUB_TOKEN }}`
          target_branch: 'master'